version: '3.3'
services:
  web:
    ports:
        - '3000:3000'
    volumes:
        - /app/node_modul
        - .:/app
    build:
      context: .
      dockerfile: Dockerfile.dev
  test:
    volumes:
        - /app/node_modul
        - .:/app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "test"]
