name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Build docker image
      run: docker build -t mohammad/docker-react -f Dockerfile.dev .
    - name: Run docker image
      run: docker run -e CI=true mohammad/docker-react npm test
