name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build, Tag & Publish Image to DockerHub
      uses: dinushchathurya/build-tag-push-action@v1.2.1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        context: .
        file: Dockerfile.dev
        repoOwner: ${{ secrets.DOCKERHUB_USERNAME }}
        repository:  nodejs-docker
        tag: mohammad/react-frontend
